import {
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  bestSellerFive,
  bestSellerSix,
  bestSellerSeven,
  bestSellerEight,
  bestSellerNine,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  newArrFive,
  newArrSix,
  newArrSeven,
  newArrEight,
  newArrNine,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "/contact",
  },
];
// =================== NavBarList End here ======================

// =================== PaginationItems Start here ===============
export const paginationItems = [
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Clay Tea Pot Set",
    price: "799",
    badge: true,
    color: "Blue",
    des: "This exquisite clay tea pot set from Clay & Crafts features a finely crafted teapot with matching cups. Each piece showcases the elegance of Shantiniketan artistry, blending tradition with a contemporary design. Perfect for serving tea with a touch of rustic charm, this set exemplifies the skill and heritage of our talented artisans.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Indian matka",
    price: "499",
    color: "Gray",
    badge: false,
    des: "This traditional Indian matka by Clay & Crafts brings the rustic charm of Shantiniketan into your home. Ideal for storing water, its natural clay composition keeps water cool. Handcrafted with intricate designs, this matka exemplifies the blend of tradition and modern style, reflecting the skill of our artisans.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Ceramic Bowl",
    price: "399",
    color: "Mixed",
    badge: true,
    des: "This elegant ceramic bowl from Clay & Crafts showcases the artistry of Shantiniketan. Perfect for serving or display, it features a sleek design that blends traditional craftsmanship with modern aesthetics. Handcrafted with care, this bowl adds a touch of sophistication and cultural charm to any setting.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Clay Pot with a Lid",
    price: "250",
    color: "Brown",
    badge: false,
    des: "This handcrafted clay pot with a lid from Clay & Crafts is a testament to Shantiniketan's artisanal excellence. Ideal for storing food or decorative use, it combines traditional craftsmanship with contemporary design. The pot's natural clay material keeps contents fresh, making it both a functional and aesthetic addition to your home.",
  },
  {
    _id: 1009,
    img: bestSellerFive,
    productName: "Colorful Bowl",
    price: "220",
    color: "Mixed",
    badge: true,
    des: "This vibrant colorful bowl from Clay & Crafts adds a lively touch to your dining experience. Handcrafted with precision, it blends traditional Shantiniketan artistry with modern aesthetics. Perfect for serving or as a decorative piece, this bowl showcases intricate patterns and a burst of colors, reflecting our artisans' creativity and skill.",
  },
  {
    _id: 1010,
    img: bestSellerSix,
    productName: "Ceramic Butter Dish",
    price: "399",
    color: "Mixed",
    badge: false,
    des: "This ceramic butter dish from Clay & Crafts combines functionality with artistic elegance. Handcrafted by skilled artisans, it features a sleek, traditional design inspired by Shantiniketan's rich heritage. Perfect for preserving and serving butter, this dish adds a touch of cultural charm and sophistication to your dining table.",
  },
  {
    _id: 1011,
    img: bestSellerSeven,
    productName: "Clay Cup",
    price: "69.00",
    color: "Mixed",
    badge: true,
    des: "The Clay Cup from Clay & Crafts embodies the rustic elegance of Shantiniketan's artistry. Handcrafted with precision, this cup blends traditional craftsmanship with modern design. Ideal for enjoying your favorite beverages, its natural clay composition enhances taste and keeps drinks cool, adding a touch of cultural heritage to your daily rituals.",
  },
  {
    _id: 1012,
    img: bestSellerEight,
    productName: "Ceramic Plates(Pack of 6)",
    price: "2029.00",
    color: "Blue",
    badge: false,
    des: "Crafted with Shantiniketan-inspired artistry, our ceramic plates offer a blend of tradition and modern design. Each set, including cups, bowls, and vases, showcases skilled craftsmanship. Perfect for everyday use or special occasions, they bring the elegance of handmade clay products directly to homes across Bangalore.",
  },
  {
    _id: 1013,
    img: bestSellerNine,
    productName: "Clay Cooking Pot with Lid",
    price: "599.00",
    color: "Brown",
    badge: false,
    des: "Combining Shantiniketan's traditional artistry with modern functionality, this pot ensures even heat distribution and enhances flavors. Crafted by skilled artisans, it’s perfect for slow cooking, adding an authentic touch to your culinary creations.",
  },
  {
    _id: 1014,
    img: newArrOne,
    productName: "Clay Cups(Pack of 6)",
    price: "379",
    color: "Brown",
    badge: true,
    des: "Clay Cups (Pack of 6) from Clay & Crafts showcase Shantiniketan-inspired artistry, crafted with traditional expertise. Each cup embodies a blend of heritage and contemporary design, perfect for elevating your dining experience.",
  },
  {
    _id: 1015,
    img: newArrTwo,
    productName: "Ceramic Water Jug",
    price: "599",
    color: "Mixed",
    badge: true,
    des: "Explore our Ceramic Water Jug, a testament to Shantiniketan's artisanal skill. Crafted with traditional expertise and modern design, it embodies the blend of heritage and contemporary elegance. Perfect for daily use or as a decorative piece, it exemplifies Clay & Crafts' commitment to quality and craftsmanship.",
  },
  {
    _id: 1016,
    img: newArrThree,
    productName: "Clay Cup",
    price: "199",
    color: "Blue",
    badge: true,
    des: "Clay Cup: Crafted with Shantiniketan-inspired artistry, our clay cups embody traditional craftsmanship fused with modern elegance. Each cup reflects the skill of our artisans, offering a unique blend of style and functionality, perfect for enhancing your everyday drinking experience.",
  },
  {
    _id: 1017,
    img: newArrFour,
    productName: "Decorative Terracotta Elephants",
    price: "799",
    color: "Brown",
    badge: false,
    des: "Decorative Terracotta Elephants: Our terracotta elephants showcase the rich artistry of Shantiniketan, blending traditional techniques with contemporary design. Each piece is meticulously crafted by skilled artisans, offering a unique and cultural touch to your home decor, celebrating the heritage of Indian craftsmanship.",
  },
  {
    _id: 1018,
    img: newArrFive,
    productName: "Blue Ceramic Bowl",
    price: "199",
    color: "Black",
    badge: true,
    des: "Blue Ceramic Bowl: Handcrafted with Shantiniketan-inspired artistry, our ceramic bowls showcase traditional craftsmanship and modern charm. Each bowl is meticulously crafted by skilled artisans, offering a blend of style and utility, ideal for elevating your dining table with elegance and functionality.",
  },
  {
    _id: 1019,
    img: newArrSix,
    productName: "Ceramic Jar",
    price: "260.00",
    color: "Black",
    badge: true,
    des: "Ceramic Jar: Inspired by Shantiniketan's artistry, our ceramic jars showcase traditional craftsmanship with a touch of modern elegance. Each jar is meticulously crafted by skilled artisans, offering a stylish and functional storage solution that adds charm to any space.",
  },
  {
    _id: 1020,
    img: newArrSeven,
    productName: "Ceramic Pot with a Lid",
    price: "224",
    color: "Mixed",
    badge: true,
    des: "Ceramic Pot with a Lid: Reflecting Shantiniketan's rich artistry, our ceramic pots are meticulously crafted, blending traditional techniques with contemporary design. Each pot, adorned with a lid, exemplifies our commitment to quality and aesthetic appeal, ideal for storing and serving with elegance in every household.",
  },
  {
    _id: 1021,
    img: newArrEight,
    productName: "Ceramic Condiment Containers",
    price: "349",
    color: "Mixed",
    badge: false,
    des: "Ceramic condiment containers: Inspired by Shantiniketan's artistry, our containers are crafted with traditional skill and modern flair. Each piece blends elegance with functionality, showcasing the craftsmanship of our artisans. Ideal for storing spices and condiments, they add a touch of charm to your dining experience.",
  },
  {
    _id: 1022,
    img: newArrNine,
    productName: "Small Clay Matka",
    price: "99",
    color: "Mixed",
    badge: false,
    des: "Small clay matka: Handcrafted with traditional Shantiniketan artistry, these small clay matkas combine elegance with practicality. Perfect for storing water or decorative purposes, each piece reflects the unique skill of our artisans, adding a touch of heritage to any space.",
  },
];
// =================== PaginationItems End here =================
